---
- name: homebrew update
  homebrew:
    update_homebrew: true
    upgrade_all: yes
  tags: homebrew

- name: homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ taps }}"
  tags: homebrew

- name: homebrew packages install
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ packages }}"
  tags: homebrew
